version: "3.9"

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres:17
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres

  cache:
    container_name: nest-clean-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
